---

- name: enable rtirq service
  systemd:
    name: rtirq
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: enable rtkit service
  systemd:
    name: rtkit-daemon
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: restart pulseAudio
  systemd:
    name: "{{ item }}"
    state: restarted
    scope: user
  with_items:
    - pulseaudio.service
    - pulseaudio.socket
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  become_user: "{{ user.name }}"
  ignore_errors: "{{ ansible_check_mode }}"
